baseurl      = "abhw0rld.com"
title        = "ABH W0RLD"
languageCode = "fr-fr"
theme        = "hello-friend-ng"
paginate     = 10

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"
  themeColor="#2A3D75"
  # Subtitle for home
  homeSubtitle = "____"
  footerLeft = "Powered by <a href=\"http://gohugo.io\">Hugo</a>" 
  footerRight = "Made with &#10084; by <a href=\"https://github.com/rhazdon\">D. Atlialp</a>"
  [params.portrait]
  path     = "/img/logo.png"
  alt      = ""
  maxWidth = "300px"
  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you linke
  enableSharingButtons = false

  # Metadata mostly used in document's head
  description = "abh w0rld ! (oo.)"
  keywords = "homepage, blog"
  images = [""]

  # Default theme "light" or "dark"
  defaultTheme = "dark"
  [[params.social]]
  name = "rootme"
  url  = "https://root-me.org/ABH"
  [[params.social]]
  name = "github"
  url = "https://github.com/iamABH"
  [[params.social]]
  name = "email"
  url  = "mailto:abh@abhw0rld.com"
[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "ABH"
    subtitle = "Cybersecurity addict !"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "+"

    [languages.en.params.logo]
      logoText = "$ ./ABH"
      logoCursorColor = "#00FEFE"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "me"
    name       = "Me"
    url        = "me/"
